### ISSUE TITLE
@iiot2k/node-red-gpio problems

### ISSUE THREAD

**Issue by JB8810** [iiot2k/iiot2k#1]
Hi,

I use your node-red nodes "@iiot2k/node-red-gpio" since I wasn't getting any data on my Pi 5 GPIOs.

Now I shutdown my pi, moved it to another location and it stopped working..
Im getting errors on the in and out nodes: "Bad file descriptor" and "chip error"

What can this be?

Regards,

Jeremy

**Comment by iiot2k** [comment]
Hi,
Open the Linux command line and enter the following command:
`gpiodetect`
You should see all the Raspberry Pi chips.
If this command also returns an error, the GPIO chip is defective.
You can also try reinstalling the node.

Regards

**Comment by N8HR** [comment]
I had a similar issue and I expect others are going to come here and might see this.

I'm running Node-RED on a RP5 in Docker.

To allow me to have access to the GPIO pins and to get rid of the "chip error"  I added 

```
        devices:
            - "/dev/gpiochip0:/dev/gpiochip0"
            - "/dev/gpiochip0:/dev/gpiochip4"
```
to my compose file. Don't know if this is the right way of doing it, but it worked for me.



Full compose.yaml (names and volumes are going to be different, mine are a relic of bad decisions and haven't bothered fixing it)

```
name: pinodered
services:
    node-red:
        stdin_open: true
        tty: true
        ports:
            - 1880:1880
        volumes:
            - nodered_node-red-data:/data
        container_name: pinodered
        image: nodered/node-red
        devices:
            - "/dev/i2c-1:/dev/i2c-1"
            - "/dev/gpiochip0:/dev/gpiochip0"
            - "/dev/gpiochip0:/dev/gpiochip4"
volumes:
    nodered_node-red-data:
        external: true
        name: nodered_node-red-data

```
